### ISSUE TITLE
Signs of PlotOwner

### ISSUE THREAD

**Issue by tonnotonato** [hskrasek/InfiniteClaims#1]
http://mcfreecraft.de/bug2.PNG

this sais enough

**Comment by hskrasek** [comment]
It says enough for the issue, but doesn't necisarily give me the info to well fix the problem lol. Also I don't use GitHubs issue system for InfiniteClaims. I am going to close this issue but if you could reopen one at hunterskrasek.com:8100 that would be great :) my only comment is that if you aren't using a even number for your plot sizes, than this could happen. It's the only documented case of this appearing.
